name: test-coverage

on:
  push:
  pull_request:

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - flag: tolerance
            filter: '^tolerance'
          - flag: bgm
            filter: '^bgm'

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::devtools
          needs: coverage

      - name: Test coverage (${{ matrix.flag }})
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          cov <- covr::package_coverage(
            type = "none",
            code = sprintf('devtools::test(filter="%s", stop_on_failure=TRUE)', "${{ matrix.filter }}")
          )
          covr::codecov(coverage = cov, flags = "${{ matrix.flag }}", quiet = FALSE)
        shell: Rscript {0}
